/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bfd.portrayalrpc.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ReqType implements org.apache.thrift.TEnum {
  ITEM(0),
  NEWS(1),
  ITEMBASE(2),
  ITEMPROFILE(3),
  NEWSBASE(4),
  NEWSPROFILE(5);

  private final int value;

  private ReqType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReqType findByValue(int value) { 
    switch (value) {
      case 0:
        return ITEM;
      case 1:
        return NEWS;
      case 2:
        return ITEMBASE;
      case 3:
        return ITEMPROFILE;
      case 4:
        return NEWSBASE;
      case 5:
        return NEWSPROFILE;
      default:
        return null;
    }
  }
}
